
apiVersion: v1
kind: Namespace
metadata:
  name: demo

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: demo
  name: hello-nginx-conf
data:
  server.conf: |
    server {
      listen 80;

      server_name hello.test;

      location /hello {
        add_header 'Content-Type' 'text/plain';
        return 200 "Hello world!\n";
      }
    }

---

apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: hello-server
spec:
  type: ClusterIP
  selector:
    app: hello-server
  ports:
  - protocol: TCP
    port: 80

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: hello-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - name: nginx
        image: nginx:1.22
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf
        configMap:
          name: hello-nginx-conf

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-misconfigured-ingress
  namespace: demo
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hello.test
    secretName: hello-test-cert-wrong-san
  rules:
  - host: hello.test
    http:
      paths:
      - path: /bad-path
        pathType: Prefix
        backend:
          service:
            name: hello-server
            port:
              number: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-good-ingress
  namespace: demo
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hello.test
    secretName: hello-test-cert
  rules:
  - host: hello.test
    http:
      paths:
      - path: /hello
        pathType: Prefix
        backend:
          service:
            name: hello-server
            port:
              number: 80
